stages:
  - test
  - e2e

variables:
  NODE_VERSION: "18"

unit-test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm ci
    - npm run test:coverage
  coverage: '/All files[^|]*\|[^|]*\s+([\d\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml

e2e-test:
  stage: e2e
  image: mcr.microsoft.com/playwright:v${NODE_VERSION}
  script:
    - npm ci
    - npx playwright install --with-deps chromium
    - npm run test:e2e
  artifacts:
    when: always
    paths:
      - playwright-report/
